### ISSUE TITLE
Create a mock of the REST api

### ISSUE THREAD

**Issue by bloodbare** [pyrenees/plone#2]
We need a REST api mock to run tests on the services that call API.

The API definition is at : http://plonerestapi.readthedocs.io/en/latest/

We can use the "import {MockBackend} from '@angular/http/testing'" that allows to overwrite the http call with a mocked backend.

https://angular.io/docs/js/latest/api/http/testing/MockBackend-class.html

There is a good example : https://gist.github.com/krimple/18393de524d99b142a7b

Deliverable:

Tests on deliverable services that creates a mock of the service.

**Comment by bloodbare** [comment]
@ebrehault @vangheem do you think that is better to use direct mocking testing or creating an external express/json-server app that can mock the api ?

**Comment by ebrehault** [comment]
@bloodbare I would go with the ng2 MockBackend, the setup will be easier, the tests will run faster.

**Comment by bcapdevilac** [comment]
I've created both karma unit tests and end-to-end tests mocking the backend using MockBackend from Angular2. Many e2e tests can't be created now because interface is not ready yet so while creating new functionalities it will be necessary completing new tests to test them, having the environment fully ready to implement them.
